### PR TITLE
Import directory with individual files

### PR DESCRIPTION
**Pull request by sisskind**
# 757

Ability to import individual shapefiles or OSM files from a directory in bulk fashion.

@brianhatchl already have a ticket to create a cucumber test (#771)

### CODE REVIEW

**Comment by sisskind** [comment]
test cucumber

**Comment by sisskind** [comment]
test this please (@sputnam is something wrong with jenkins?)

**Comment by sisskind** [comment]
test this please

**Comment by brianhatchl** [comment]
jenkins run cucumber

**Comment by sisskind** [comment]
Will fail until fix to #771

**Comment by brianhatchl** [comment]
Wow!  A new 1000 line js file ;-)
Does this allow selecting a directory and implicitly all files within it?  Or is it selecting multiple files within a directory?
I thought we had this for selecting multiple shapefiles in the past.

**Comment by sisskind** [comment]
Ugh -- is it really 1000 lines?  May be a candidate for refactoring down the road.

This allows for selecting multiple shapefiles or OSM files within the same directory and attributing one translation, folder, etc.  This method loads each shapefile or OSM separately, not as the same dataset.  It had been set to import a directory, but that is not currently supported on firefox.  After talking with stakeholders, the current implementation is the desired one.

**Comment by brianhatchl** [comment]
Okay, thanks.  So I'll merge https://github.com/ngageoint/hootenanny/pull/1166 and then this and #781.

Hope the two ui PRs both merge cleanly.  There seems to be a lot of similarity in the changes.  Is one a superset of the other?

**Pull request merged**
