### PR TITLE
756

### PR DESCRIPTION
**Pull request by jcp2236**
Changed to arrows

### CODE REVIEW

**Comment by sisskind** [comment]
```
 (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/custom_steps.rb:882:in `/^I should see an invalid input warning for "([^"]*)"/'
features/advanced_options_invalid_input.feature:54:in `Then I should see an invalid input warning for "#element_cache_size_node"'
features/advanced_options_invalid_input.feature:32:in `Then I should see an invalid input warning for "#<element>"'

Failing Scenarios:
cucumber features/advanced_options_invalid_input.feature:54 # Scenario Outline: Check for Invalid Inputs in Reference Advanced Options, Examples (#3)
```

**Comment by brianhatchl** [comment]
run cucumber

**Comment by jcp2236** [comment]
run cucumber

**Comment by sisskind** [comment]
run cucumber

**Comment by sisskind** [comment]
this passes locally

**Comment by jcp2236** [comment]
run cucumber

**Comment by brianhatchl** [comment]
Taking a look at this again, and testing it out, it seems to me that the behavior of the next review request does return results in a predictable order.  The http request includes an `offsetseqid` param that gets mapped to the tag `hoot:review:sort_order` when doing a query against review relations in the db.

**Comment by jcp2236** [comment]
Interesting. I'd like to take a look at that code so I can get a better idea of how it works in the db (I didn't poke around in there, just the ui). Sounds like the issue this ticket solves may not be an issue to begin with.

**Comment by brianhatchl** [comment]
https://github.com/ngageoint/hootenanny/blob/develop/hoot-services/src/main/java/hoot/services/controllers/review/ReviewResource.java#L215-L258

**Comment by jcp2236** [comment]
Thanks

**Comment by sisskind** [comment]
OBE

**Pull request closed without merging**
