### PR TITLE
UI support for Conflate/Export OSM API database data in iD Editor #386

### PR DESCRIPTION
**Pull request by brianhatchl**

### CODE REVIEW

**Comment by bwitham** [comment]
Oh, yeah...forgot about this formatting thing with the js.  What's the quickest way to clean up my mess?

**Comment by brianhatchl** [comment]
You can run npm test from the hoot-ui folder to check locally.  ESLint will tell you what it's complaining about.

**Comment by brianhatchl** [comment]
You can try running `node_modules/.bin/eslint --fix js/id` and `node_modules/.bin/eslint --fix js/hoot` to autocorrect as much as possible.

**Comment by bwitham** [comment]
cool, thanks.  will do tomorrow.

**Comment by bwitham** [comment]
fixed eslint issues

**Pull request merged**
