### PR TITLE
Do not use layer name in CSS

### PR DESCRIPTION
**Pull request by sisskind**
#578

### CODE REVIEW

**Comment by sisskind** [comment]
To test:

1. Load reference dataset
2. Press ALT+N. Dataset visibility should change.
3. Load secondary dataset
4. Press ALT+N. Both datasets should be hidden. Press ALT+N again to view them.
5. Run conflation job.
6. Press ALT+N to hide layers. Run again to view them.
7. Press ALT+B to toggle layer visibility.

**Comment by sisskind** [comment]
run cucumber

**Comment by sisskind** [comment]
run cucumber

**Comment by briandaviddavidson** [comment]
run cucumber

**Comment by briandaviddavidson** [comment]
run cucumber

**Comment by sisskind** [comment]
run cucumber

**Comment by sisskind** [comment]
run cucumber

**Comment by sisskind** [comment]
@brianhatchl I think it is safe to merge...

**Pull request merged**
