### PR TITLE
Improve Bulk Export Form and Differentiate Translations

### PR DESCRIPTION
**Pull request by sisskind**
Straightforward - same as Bulk Import #935

### CODE REVIEW

**Comment by brianhatchl** [comment]
I see some OSM label updates needed:
>                {'DESCRIPTION': 'Open Street Map (OSM)'},
>                {'DESCRIPTION': 'Open Street Map (PBF)'}
Suggest the top one might be (XML).

**Comment by sisskind** [comment]
Is that pulling from UI or Core?

**Comment by brianhatchl** [comment]
https://github.com/ngageoint/hootenanny-ui/blob/d2e968bde5440311a808cb8508c7cc49f176b09b/js/hoot/control/utilities/BulkExportDataset.js#L53-L58

**Comment by sisskind** [comment]
@brianhatchl Roger - that may be the way its been for a while.

**Comment by sisskind** [comment]
Merged 'differentiate translations' branch to solve cucumber test issue in one PR.

**Comment by sisskind** [comment]
https://github.com/ngageoint/hootenanny-ui/issues/938

**Comment by sisskind** [comment]
run :cucumber:

**Comment by sisskind** [comment]
Waiting on fix for specific cucumber test.

**Comment by sisskind** [comment]
www.github.com/digitalglobe/vgi-team-repo/issues/931

**Comment by sisskind** [comment]
run 🥒

**Comment by rmrice** [comment]
run :cucumber:

**Comment by sisskind** [comment]
run :cucumber:

**Comment by sputnam** [comment]
death by :cucumber:

**Comment by brianhatchl** [comment]
Seems like there was a vagrant change so that tomcat deployed filed hootenanny-id and hoot-services.war are not owned by vagrant (instead of tomcat8).  I updated the VagrantfileLocal for ubuntu1404 on dockson to run the ActivateEGDplugin.sh script as vagrant.

run :cucumber:

**Comment by brianhatchl** [comment]
Missed a change in the job config.  run :cucumber:

**Comment by brianhatchl** [comment]
run :cucumber:

**Comment by brianhatchl** [comment]
run :cucumber:

**Comment by brianhatchl** [comment]
run :cucumber:

**Comment by brianhatchl** [comment]
run :cucumber:

**Comment by brianhatchl** [comment]
keep fixing jenkins workspace corruptions, run :cucumber:

**Comment by brianhatchl** [comment]
at least it failed with a test error this time.  run :cucumber:

**Pull request merged**
