### PR TITLE
Issue #450 : handle variable numbers of relation members

### PR DESCRIPTION
**Pull request by treycaldwell**
@mingjiesu will merge https://github.com/ngageoint/hootenanny/issues/136 into hoot develop which is needed for this pull.

### CODE REVIEW

**Comment by sisskind** [comment]
@treycaldwell Great work, but would like to see test pass.  @brianhatchl is there a way to trigger the test before we merge?

**Comment by brianhatchl** [comment]
There is now,
jenkins test this please

**Comment by brianhatchl** [comment]
/jenkins/hoot-ui-pull-request/js/hoot/control/conflicts/map/FeatureHighlighter.js
  111:26  error  Expected '===' and instead saw '=='  eqeqeq
  125:26  error  Expected '===' and instead saw '=='  eqeqeq

✖ 2 problems (2 errors, 0 warnings)

**Comment by sisskind** [comment]
Thanks @brianhatchl.  Will fix.

**Pull request merged**
