### PR TITLE
try logo version with sewing font

### PR DESCRIPTION
**Pull request by brianhatchl**
screenshot from 2017-01-23 11 12 12

For comparison with:
screenshot from 2017-01-25 16 11 13

### CODE REVIEW

**Comment by brianhatchl** [comment]
@rmrice y u no likey?

**Comment by rmrice** [comment]
From a designer perspective, it doesn't fit. I like the other one much better. Maybe @briandaviddavidson and @sisskind can weigh in here.

**Comment by brianhatchl** [comment]
jenkins run cucumber

**Comment by brianhatchl** [comment]
run cucumber

**Comment by rmrice** [comment]
Maybe it's a sign 🤔

**Comment by brianhatchl** [comment]
<grumble> :angry:

**Pull request closed without merging**
