### PR TITLE
#423

### PR DESCRIPTION
**Pull request by sisskind**
Please refer to https://github.com/ngageoint/hootenanny-ui/pull/427 for additional notes.

### CODE REVIEW

**Comment by sisskind** [comment]
@brianhatchl new branch is 423-2.  423 will no longer be updated and will be deleted.  Created new branch to avoid detached head due to reverted code.

**Comment by sisskind** [comment]
@sisskind -- note for self:  determine if there is a way to see if relation exists before running through LoadFromURL (@brianhatchl chime in if you are familiar with a method).  Currently looking through Java service code to determine if this method exists.  All I have found thus far is a call to load relations (http://localhost:8080/hoot-services/osm/api/0.6/relations?mapId=1036&elementIds=3). Ideally, I would like to use this to get all relation ids.  If successful, this will eliminate the warnings in the console that the website is not available.

**Comment by brianhatchl** [comment]
I think a 404 for a request for a deleted relation isn't the worse thing.  That's the way REST is supposed to work.

**Comment by sisskind** [comment]
Okay - if we are okay with the 404 appearing in console then this may be done. Will give one more pass to test.

**Comment by sisskind** [comment]
@brianhatchl Think this is ready for review, with two caveats:

1. You will still see 404 errors in the console when saving an empty relation of ways.  This will be addressed in #439.
2. Empty point relations are not being deleted.  This will be addressed in #428.

How to test:
- Run conflation job with nodes as features
- Delete all red/blue features and get no error messages
- Click Resolve, get no error messages in UI
- Repeat with next review (delete...)
- Click Save, get no error messages in UI
- Repeat for ways

**Pull request merged**
