### PR TITLE
make alert messages look better

### PR DESCRIPTION
**Pull request by rmrice**
#776 

Before:
screenshot from 2016-10-20 13 48 28

After:
screenshot from 2016-10-20 13 40 51

### CODE REVIEW

**Comment by brianhatchl** [comment]
jenkins run cucumber

**Comment by brianhatchl** [comment]
run cucumber

**Comment by brianhatchl** [comment]
The alert changes seems to have broken the custom step used to close the alert bubble in this test:
```
(::) failed steps (::)

unknown error: Element is not clickable at point (1864, 146). Other element would receive the click: <p>...</p>
  (Session info: chrome=49.0.2623.87)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.13.0-85-generic x86_64) (Selenium::WebDriver::Error::UnknownError)
./features/step_definitions/custom_steps.rb:496:in `/^I close the UI alert$/'
features/z_conflate_export_osm_api_db.feature:86:in `Then I close the UI alert'

Failing Scenarios:
cucumber features/z_conflate_export_osm_api_db.feature:50 # Scenario: Export Dataset into an OSM API Database With Conflicts
```

**Comment by rmrice** [comment]
For some reason changing `<h3>` to `<p>` messed things up. I'm fixing it now.

**Comment by briandaviddavidson** [comment]
Alert messages look good :+1:

**Pull request merged**
