### PR TITLE
#560 Removing shadow on map move

### PR DESCRIPTION
**Pull request by sisskind**
#560 

By removing the shadow class on map move, the delayed shadow drawing no longer occurs.  This line had been commented out, but cannot find supporting evidence as to why.

### CODE REVIEW

**Comment by brianhatchl** [comment]
Can't merge this.  The review feature halos use the shadow and this commit causes the red and blue highlights to be removed.

**Comment by sisskind** [comment]
@brianhatchl can you take another look?

**Comment by brianhatchl** [comment]
It's not working for me.  Does it work in your testing?

**Comment by brianhatchl** [comment]
The activeReviewFeature class is on the parent <g> not the <path>

**Comment by sisskind** [comment]
@brianhatchl did work for me (at least I think it did).  Was able to see both features in review pair highlighted as red and blue.  Is that not what you are referring to?

**Comment by brianhatchl** [comment]
yeah, I don't see halos.  they only appear when dragging the feature

**Comment by sisskind** [comment]
Will give it another shot now.  Are you experiencing for all geom types or just paths?

**Comment by brianhatchl** [comment]
it's POIs in my case, but the svg shadow is a path element

**Comment by sisskind** [comment]
Get red/blue features, but the yellow highlight does disappear.  Fixing that.

**Comment by sisskind** [comment]
So it appears that removing the shadow will break the yellow highlight for edited features.  Back to the drawing board...

**Comment by sisskind** [comment]
Yes -- seeing it with POIs now too.  Really back to the drawing board this time.

**Comment by sisskind** [comment]
Now see what you mean w/points where shadow is child of parent.

**Comment by brianhatchl** [comment]
Looks good now.  Do we only need to remove only the line layer shadows to avoid the flickering this ticket is meant to address?

**Pull request merged**
