### PR TITLE
port refactored schema switcher to hoot-ui

### PR DESCRIPTION
**Pull request by brianhatchl**
refs #790

### CODE REVIEW

**Comment by brianhatchl** [comment]
relies on some cucumber test updates, see https://github.com/ngageoint/hootenanny/pull/1223 for passing test jobs

**Comment by brianhatchl** [comment]
jenkins run npm test

**Comment by sisskind** [comment]
run cucumber

**Comment by sisskind** [comment]
Will review later tonight now that tests are passing.

**Comment by sisskind** [comment]
All looks good, but want to get a better handle overall on what this means for greater Hoot.

**Pull request merged**
