### PR TITLE
Remove duplicate code causing multiple user icons

### PR DESCRIPTION
**Pull request by briandaviddavidson**
Same testing flow as https://github.com/ngageoint/hootenanny-ui/pull/615

### CODE REVIEW

**Comment by brianhatchl** [comment]
jenkins please run cucumber

**Comment by brianhatchl** [comment]
Another cucumber false positive.  The app isn't initializing as indicated by the first failed feature and the blank screenshot.

jenkins please re run cucumber

**Comment by briandaviddavidson** [comment]
@jcp2236 Can you take a look and merge?

**Comment by jcp2236** [comment]
Works as intended based on the #615 testing workflow

**Pull request merged**
