### PR TITLE
Check for valid coordinates

### PR DESCRIPTION
**Pull request by sisskind**
New function checks for valid coordinates when panning to entity.

@brianhatchl can you take a quick look -- should be an easy one.  Thanks.

This is a potential mitigation for #424, but will need to replicate the error to fully confirm.

### CODE REVIEW

**Comment by brianhatchl** [comment]
It seems like several things could be going wrong that this PR is meant to mitigate.  

- entity extent not defined
- entity not in graph
- entity loc is invalid
- map extent not defined
- map extent is invalid
- map extent coords are invalid

Do we care what/why it is happening?  Or are we satisfied that when it does happen the code handles the error?

**Comment by brianhatchl** [comment]
The San Diego conflated waterways datasets produce this error for me, but it's not "on command".  Some combination of resolving or skipping reviews will make it occur.

**Comment by sisskind** [comment]
I will try with this dataset and see if I can get it to cause error.  Did error occur within branch or on current develop?

**Comment by brianhatchl** [comment]
This branch.  The error was handled, but I saw the "Could not locate selected feature with id:" error alert.

**Comment by sisskind** [comment]
Oh -- then that should be considered a win.  Point is to catch error and not go into NaN NaN.

**Comment by sisskind** [comment]
Wait -- hold off on merging PR.  May have found root of issue.

**Comment by sisskind** [comment]
It looks like some features have an extent of 'Infinity'.  The code above should mitigate that and throw the error.  Digging a touch deeper to see if the actual coordinates can be extracted.  If not, will keep this as is to mitigate the NaN issue.

**Comment by sisskind** [comment]
@brianhatchl I think this is okay to go.  The error is going to catch any NaN values and will not allow iD to get "lost in space".  Is there a concern over the error message even if it does eventually get there?

**Comment by brianhatchl** [comment]
Nope.  I will merge.

**Comment by sisskind** [comment]
:)

**Pull request merged**
