### PR TITLE
Fix eslint and mocha tests

### PR DESCRIPTION
**Pull request by brianhatchl**
The jenkins job hoot-ui-pull-request will run `make && npm test` which will run javascript source code through eslint and run mocha tests and report any failure.

### CODE REVIEW

**Comment by brianhatchl** [comment]
@sisskind Do we want to merge this and start with the eslint checks and partial passing mocha tests?
Then we can fix/enable more tests in another branch/pull request?

This is assuming this branch is usable as the UI in a browser, which I shall test now.

**Comment by brianhatchl** [comment]
Conflation review isn't zooming to review features as expected or coloring them according to merged/input source.

**Comment by sisskind** [comment]
The non zooming may be unrelated to merge, but we can dig in on that.  I was able to run some smoke tests but would like to test a little more before merge.  @mjeffe98 can you pull down the 343 branch and run a smoke test?

**Comment by brianhatchl** [comment]
I was thinking it was due to the eslint/mocha changes.

**Comment by sisskind** [comment]
i think i remember seeing this before the eslint fixes though.

**Comment by brianhatchl** [comment]
@sisskind ready to merge

**Comment by sisskind** [comment]
And it was done.

**Pull request merged**
