### PR TITLE
group & sort advanced options list elements.

### LINKED ISSUE #1567: ensure adv options order with sort function
It'd be helpful to have control of advanced options list sort order. we should add some code to the front end to do this.

### PR DESCRIPTION
**Pull request by maxgrossman**
closes #1567

### CODE REVIEW

**Review by brianhatchl — COMMENTED** [review]
what if we gave these an order property in the json and just used that to sort?

**Comment by maxgrossman** [comment]
Maybe, but if we imply sort by the order of the objects in that file can't we just do that.

**Comment by maxgrossman** [comment]
rather than add more code.

**Comment by brianhatchl** [comment]
Even better, let's just reorder https://github.com/ngageoint/hootenanny/blob/master/conf/services/conflationTypes.json

**Pull request closed without merging**
