### PR TITLE
#453

### PR DESCRIPTION
**Pull request by sisskind**
How to test (can also refer to #453)

1) Open up a dataset that has reviews
2) Go to a review that has a blue and a red feature (I have had it work with just a red feature but it wasn't reliable)
3) Click a feature so the pallet appears
4) Click and hold on another feature (I usually click a road) and then drag/pan the screen until the radial menu disappears
5) Should now ~~be experiencing a phantom pallet~~ see the radial menu again.

The fix was setting the radialMenu to undefined, which was not happening if you were clicking, holding, and panning.

### CODE REVIEW

**Comment by brianhatchl** [comment]
I was able to reproduce this and the bug seems to occur after this js error is thrown:
```
d3.min.js:5 Uncaught TypeError: Cannot read property 'count' of undefined
```
However, there is no info in the call stack to indicate what iD or Hoot method led to this.

I'll pull the branch and see if I can still reproduce the bug or not.

**Comment by sisskind** [comment]
@Brianhatchl it is in the radial_menu.js file. What is happening is the function to close the menu is being called but the svg had already been closed, hence the undefined. I thought setting ```radialmenu = undefined``` would solve this so the menu would not try to close, but apparently didn't totally cover issue.

**Comment by brianhatchl** [comment]
So my above comment was just about reproducing the bug before the fix.  It is finicky to reproduce, but I have still been able to do so on the PR #453 branch.  The error is occurring after the select/drag pan, when a new feature is clicked to select it.  So would the code path be for opening the radial menu?

Again, some of the elements are actually there, just invisible because hovering over the area will reveal the tooltip for "Straighten this line" menu item.

**Comment by brianhatchl** [comment]
Using the dev console inspector, the opacity property of the radial-menu <g> element is still set to zero.  I don't know if that gives a clue to where in the code something may be going wrong.

**Comment by sisskind** [comment]
I think the opacity 0 is a result of the code breaking. Believe the radial menu closing script is where the error is occurring, since it is trying to close something that has already closed.

**Comment by briandaviddavidson** [comment]
run cucumber

**Comment by sisskind** [comment]
@brianhatchl this is due to the radial menu not properly closing (https://github.com/ngageoint/hootenanny-ui/blob/453/js/id/ui/radial_menu.js#L127)

> Using the dev console inspector, the opacity property of the radial-menu element is still set to zero. I don't know if that gives a clue to where in the code something may be going wrong.

**Comment by sisskind** [comment]
@brianhatchl can you retest?  Setting ```radialMenu = undefined``` on move.select may solve problem, as it will prevent the radialMenu from trying to close in rapid succession, leading to the error.

**Comment by sisskind** [comment]
test this please

**Comment by brianhatchl** [comment]
If you push new commits, jenkins will retest.  No need to issue a comment.

**Comment by sisskind** [comment]
Looks like cucumber test has conflict with pbf format.  Will investigate and update.

CC @briandaviddavidson @treycaldwell @brianhatchl

**Pull request merged**
