### PR TITLE
Export options

### PR DESCRIPTION
**Pull request by sisskind**
https://github.com/DigitalGlobe/VGI-team-repo/issues/581

tagoverride

### CODE REVIEW

**Comment by mattjdnv** [comment]
Nice work!

**Comment by mattjdnv** [comment]
Cucumber!

Also, looking at the Jenkins job, I think it is supposed to have the matching branch for Hoot:
```
+ cd hootenanny
+ git fetch
From https://github.com/ngageoint/hootenanny
   a708b90..16ec89c  1797       -> origin/1797
 * [new branch]      1797-global-pois -> origin/1797-global-pois
 * [new branch]      1988       -> origin/1988
   55bd974..6e4743a  export-options -> origin/export-options
   5565dd3..a3da605  jenkinstest -> origin/jenkinstest
Fetching submodule hoot-ui
From https://github.com/ngageoint/hootenanny-ui
   9a33761..932adbe  994        -> origin/994
   26addfe..f049dba  export-options -> origin/export-options
+ git checkout master
Switched to branch 'master'
M	hoot-ui
Your branch is behind 'origin/master' by 272 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
+ git pull
Updating 7f37adb..35f0a13
```

**Comment by mattjdnv** [comment]
run cucumber!

**Comment by brianhatchl** [comment]
The jenkins ui job uses the PR target branch for the main hoot repo.  In most cases this is develop.  So if a needed service change was not yet merged in, that could account for the test failure.  If there is a PR that requires both UI and services updates, I usually include a hoot-ui submodule update to the UI PR branch commit in the hoot PR so both branch versions will be correct.

**Comment by mattjdnv** [comment]
I merged the services changes a while ago so they are in develop. I don't think @sisskind built a cucumber test for this task.

**Comment by mattjdnv** [comment]
Trying again:  death by cucumber!

**Comment by brianhatchl** [comment]
idk why that didn't work.  run :cucumber:

**Comment by brianhatchl** [comment]
I've seen this test fail before and thought I added a fix a week or so ago.  Checking commit history now.

**Comment by brianhatchl** [comment]
The fix I'm thinking of is in there https://github.com/ngageoint/hootenanny/commit/8534351e3d61413066b8d4a282d4a0c4e5102690#diff-26a1e619dcb43f84c41fceafc37cf027R21

**Comment by brianhatchl** [comment]
Seems like this job might not be loading the latest hoot develop becuase
```
stale element reference: element is not attached to the page document
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 3.13.0-135-generic x86_64) (Selenium::WebDriver::Error::StaleElementReferenceError)
features/hide_map_features.feature:22:in `And I click the "div" with text "Zoom to Layer"'

Failing Scenarios:
cucumber features/hide_map_features.feature:3 # Scenario: I can hide map features in review mode
```
The failing line should be 23 in the latest code https://github.com/ngageoint/hootenanny/blob/develop/test-files/ui/features/hide_map_features.feature#L23

**Comment by brianhatchl** [comment]
Hmmm...
```
+ cd hootenanny
+ git fetch
From https://github.com/ngageoint/hootenanny
   ba19b2e..06b8abc  develop    -> origin/develop
+ git checkout master
Switched to branch 'master'
M	hoot-ui
Your branch is up-to-date with 'origin/master'.
+ git pull
Already up-to-date.
```

This should be develop branch.

**Comment by brianhatchl** [comment]
why @sisskind why?
image

**Comment by sisskind** [comment]
Because I was rushing...

**Pull request closed without merging**
