### PR TITLE
#377 Will load review layer if input layer(s) have been deleted

### PR DESCRIPTION
**Pull request by sisskind**

### CODE REVIEW

**Comment by sisskind** [comment]
@brianhatchl can you review?

**Comment by sisskind** [comment]
Error with coloring and moving to next during review.  Will keep ticket open.

**Comment by sisskind** [comment]
@brianhatchl can you review again please?

**Comment by brianhatchl** [comment]
The ui still seems to hang when one of the input layers has been removed.
screenshot from 2016-05-05 11 28 00

**Comment by sisskind** [comment]
What dataset were you using?

**Comment by sisskind** [comment]
Will test again on my end and see if I get same results.  Had tested with all 4 scenarios (both datasets present, reference missing, secondary missing, both missing) and had passed them all.

**Comment by sisskind** [comment]
@brianhatchl Cannot replicate issue.  Are you sure you have latest code?

**Comment by brianhatchl** [comment]
my b... my b

**Comment by sisskind** [comment]
it's all good -- we can blame it on your knee.

**Comment by brianhatchl** [comment]
Actually, it must've been git gui.  It was showing 377, but I must have been on develop

**Comment by brianhatchl** [comment]
One thing I notice.  If you select a feature and use the toggle with input layers button on the radial menu, all the features disappear and using the layer list to make the merged layer visible doesn't seem to work either.  Is there a way to recover from this?

**Comment by sisskind** [comment]
Have not experienced that -- am able to use Background sidebar to turn merged layer back on.  Had thought that maybe it would be prudent to not allow users to toggle if one/both of input layers were missing (which would avoid that issue altogether).

**Comment by brianhatchl** [comment]
Do you wish to track that in a separate ticket?  This PR is an improvement on existing behavior.

**Comment by sisskind** [comment]
Sounds good to me.  https://github.com/ngageoint/hootenanny-ui/issues/417

**Pull request merged**
