### PR TITLE
#264 Show all reviews

### PR DESCRIPTION
**Pull request by sisskind**
#264

### CODE REVIEW

**Comment by sisskind** [comment]
@brianhatchl can you review and merge?

**Comment by brianhatchl** [comment]
One thing I'm noticing is that if a review is marked resolved.  The review link remains on the screen and can still be shown from the radial menu.  I think once the review is resolved, that link (I know the relation is still in the data, but is marked hoot:needs:review=no) should be invisible to the user.

**Comment by brianhatchl** [comment]
The other thing I noticed once, but cannot recreate is when a bunch of related pois have flashing blue halos.  It really obscured which review points were red and blue when navigating with the show related radial menu.

**Comment by sisskind** [comment]
@brianhatchl Thanks for feedback. Will update and tag you when ready here for review.

**Comment by sisskind** [comment]
@brianhatchl changes have been made.  Can you re-review?

**Comment by brianhatchl** [comment]
I'm still seeing behavior where an already resolved review is showing up in the "Show review relations" graph.

Here is the scenario I'm testing:
1. Find a review where the review feature needs to be reviewed against two other features.
2. Click the review feature to show the radial menu and select the "Show review relations" button.
3. Click either relation letter to set the active review.
4. Mark this review as resolved (indicating these are two separate features).

What I would like to see happen:
1. After resolving review, the "Show review relations" setting persists, showing only the remaining review edge to the remaining review against feature.

What I'm seeing now:
1. The previous review item remains selected (that's good, instead of a random new review feature).
2. But when I click the item and "Show review relations" I still edges for both reviews.
3. Clicking the resolved review item (circled letter) I get the warning "Review item has already been resolved".

**Comment by sisskind** [comment]
@brianhatchl Made update so that resolved reviews do not get bubble to select or line connecting.  Can you review/merge?

**Comment by brianhatchl** [comment]
I'm still not seeing what I expect.  It almost seems like selecting the relation bubble is selecting the correct features and showing them in the tag table, but resolving the review may be resolving the one originally selected by the next button.

I'm using the conflated DC POI data and the review feature that has multiple review against features is Kalorama Park located at http://localhost:8080/#map=18.78/-77.04447/38.92027

**Comment by sisskind** [comment]
@brianhatchl I can talk to customer again, but showed them demo and they were okay with current method (do not go to review until you click the bubble) as opposed to driving to review when clicking 'show relations'.  Is that what you are referring to?

**Comment by sisskind** [comment]
@brianhatchl found a bug -- please hold on merging.  Will update here when ready.

**Comment by brianhatchl** [comment]
Was there a commit for the bug you just found?

I'll show you what I mean on Monday.

**Comment by sisskind** [comment]
No -- I think it has to do with similar issues w/share reviews.  Will create a ticket but makes sense to incorporate here.  Sounds good RE: Monday.

**Comment by sisskind** [comment]
@brianhatchl Can you review?  Let me know if this meets what you were seeing, and I will merge in with develop based on upstream merge.

**Comment by brianhatchl** [comment]
I will, but can you resolve the merge conflicts with develop first?

**Comment by sisskind** [comment]
Sure -- wasnt sure if you were going to pull down that specific branch.  Stand by.

**Comment by brianhatchl** [comment]
What I meant was merge develop into this branch, so the PR will merge back cleanly

**Comment by sisskind** [comment]
Replaced by https://github.com/ngageoint/hootenanny-ui/pull/350

**Comment by sisskind** [comment]
figured it was easier to go this --> dev based on upstream merge

**Pull request closed without merging**
