### PR TITLE
Fix Advanced Options Label

### PR DESCRIPTION
**Pull request by rmrice**
Label stays where it's supposed to now :see_no_evil:

### CODE REVIEW

**Comment by rmrice** [comment]
run cucumber

**Comment by rmrice** [comment]
```
error: Your local changes to the following files would be overwritten by checkout:
	missing
Please, commit your changes or stash them before you can switch branches.
Aborting
```

???

**Comment by brianhatchl** [comment]
run cucumber

**Comment by brianhatchl** [comment]
@rmrice Just like the error states, the git repo on the jenkins vm had a modifed file tracked by git `missing` (which is used by the c++ compiler I think).  The jenkins job does a `git pull` from the develop branch and it was unable to do so because the `missing` file was modified and would be overwritten.  Same thing would happen on your local git repo if you had changed tracked files and tried to pull.

I solved it this once by ssh'ing to the jenkins vm and doing `git checkout -- missing` to restore the state of the file from the most recent commit so that git pull would succeed.

**Pull request merged**
