### PR TITLE
#229 Fix imagery validation ui code for reviews as relations

### PR DESCRIPTION
**Pull request by brianhatchl**
To test, run Prepare for Validation on a dataset and then add the dataset to the map.  The UI should prompt the user to enter the imagery validation workflow.

The choice buttons should then set certain tags on the validated feature and proceed to the next review item.  As validation review items are resolved, the relation is deleted.  After all items are handled, the dataset should have no more review relations.  These should be removed:
```
    <relation visible="true" id="1" timestamp="2016-02-12T15:30:50Z" version="1" changeset="163">
        <member type="node" ref="29" role="reviewee"/>
        <tag k="hoot:review:type" v="Validation"/>
        <tag k="hoot:review:needs" v="yes"/>
        <tag k="hoot:review:choices:1" v="{&quot;label&quot;:&quot;Confirmed&quot;,&quot;description&quot;:&quot;You can look at the point and tell what it is (e.g. mosque or airport)&quot;,&quot;changes&quot;:{&quot;replaceTags&quot;:{&quot;hgis:imagery_confirmed&quot;:&quot;confirmed&quot;,&quot;hgis:accuracy&quot;:&quot;high&quot;},&quot;appendTags&quot;:{&quot;source:geometry&quot;:&quot;${BASEMAP_IMAGE_SOURCE}&quot;,&quot;source:geometry:sensor&quot;:&quot;${BASEMAP_IMAGE_SENSOR}&quot;,&quot;source:geometry:date&quot;:&quot;${BASEMAP_IMAGE_DATETIME}&quot;,&quot;source:geometry:id&quot;:&quot;${BASEMAP_IMAGE_ID}&quot;}}}"/>
        <tag k="hoot:review:choices:2" v="{&quot;label&quot;:&quot;Assessed&quot;,&quot;description&quot;:&quot;The point is on a building, but you can't verify its type (e.g. hair salon).&quot;,&quot;changes&quot;:{&quot;replaceTags&quot;:{&quot;hgis:imagery_confirmed&quot;:&quot;assessed&quot;,&quot;hgis:accuracy&quot;:&quot;high&quot;},&quot;appendTags&quot;:{&quot;source:geometry&quot;:&quot;${BASEMAP_IMAGE_SOURCE}&quot;,&quot;source:geometry:sensor&quot;:&quot;${BASEMAP_IMAGE_SENSOR}&quot;,&quot;source:geometry:date&quot;:&quot;${BASEMAP_IMAGE_DATETIME}&quot;,&quot;source:geometry:id&quot;:&quot;${BASEMAP_IMAGE_ID}&quot;}}}"/>
        <tag k="hoot:review:choices:3" v="{&quot;label&quot;:&quot;Reported&quot;,&quot;description&quot;:&quot;Imagery is pixelated or cloudy -- can not be assessed.&quot;,&quot;changes&quot;:{&quot;replaceTags&quot;:{&quot;hgis:imagery_confirmed&quot;:&quot;reported&quot;},&quot;appendTags&quot;:{&quot;source:geometry&quot;:&quot;${BASEMAP_IMAGE_SOURCE}&quot;,&quot;source:geometry:sensor&quot;:&quot;${BASEMAP_IMAGE_SENSOR}&quot;,&quot;source:geometry:date&quot;:&quot;${BASEMAP_IMAGE_DATETIME}&quot;,&quot;source:geometry:id&quot;:&quot;${BASEMAP_IMAGE_ID}&quot;}}}"/>
        <tag k="hoot:review:score" v="1"/>
        <tag k="hoot:review:note" v="Flagged for imagery validation"/>
        <tag k="type" v="review"/>
        <tag k="error:circular" v="0"/>
    </relation>
```

and 30% of the features should have validation tags.  Validated vs unvalidated feature:
```
    <node visible="true" id="4" timestamp="2016-02-11T23:46:33Z" version="1" changeset="126" lat="38.9217184000000032" lon="-77.0308200999999997">
        <tag k="addr:full" v="1312 CLIFTON STREET NW"/>
        <tag k="source:ingest:datetime" v="2015-06-01T17:43:03.079Z"/>
        <tag k="name" v="WARDMAN COURT APARTMENTS"/>
        <tag k="error:circular" v="15"/>
    </node>
    <node visible="true" id="5" timestamp="2016-02-11T23:50:09Z" version="2" changeset="134" lat="38.9172125999999992" lon="-77.0436645999999996">
        <tag k="addr:full" v="2001 19TH STREET NW"/>
        <tag k="source:ingest:datetime" v="2015-06-01T17:43:03.052Z"/>
        <tag k="hgis:imagery_confirmed" v="assessed"/>
        <tag k="source:geometry" v="Bing"/>
        <tag k="hgis:accuracy" v="high"/>
        <tag k="hoot" v="dcpoivalid5"/>
        <tag k="name" v="COLEY REED"/>
        <tag k="error:circular" v="15"/>
    </node>
```
If the EGD plugin is active and additional images are added to the map, the validation tags will contain additional metadata:
```
    <node visible="true" id="21" timestamp="2016-02-12T15:33:03Z" version="2" changeset="164" lat="38.9199101999999968" lon="-77.0345592999999980">
        <tag k="addr:full" v="2307 15TH STREET NW"/>
        <tag k="source:ingest:datetime" v="2015-06-01T17:43:03.129Z"/>
        <tag k="hgis:imagery_confirmed" v="assessed"/>
        <tag k="source:geometry" v="Bing;DigitalGlobe GBM - 62b0b9b959be7927eddbf37eff670524;DigitalGlobe GBM - caa9a756ba4f88b35482d47180c8661c"/>
        <tag k="source:geometry:sensor" v="WV03_VNIR;WV02"/>
        <tag k="source:geometry:id" v="62b0b9b959be7927eddbf37eff670524;caa9a756ba4f88b35482d47180c8661c"/>
        <tag k="hgis:accuracy" v="high"/>
        <tag k="source:geometry:date" v="2016-02-11 16:27:53;2016-02-02 15:51:01"/>
        <tag k="hoot" v="dcpoivalid6"/>
        <tag k="name" v="THE LOFTS AT MERIDIAN HILL CONDOMINIUMS"/>
        <tag k="error:circular" v="15"/>
    </node>
```

### CODE REVIEW

**Comment by sisskind** [comment]
@brianhatchl Want to confirm that the zoom function w/in loadEntity that has been removed will still zoom to feature when loaded.  Seems like this is now within a loadFeature function, but wanted to double check.

**Comment by brianhatchl** [comment]
What was bugging me was the context.loadEntity was being redefined further down in id.js and it didn't seem like anyplace else was calling that method, so I wanted to restore it to the default iD code.

But I do see it now being called by zoomToEntity, so I may have in fact broken something.

**Comment by brianhatchl** [comment]
Grep'ing around, I only see these calls to context.loadEntity and context.zoomToEntity:
```
Searching 297 files for "context.loadEntity" (regex)

/home/bhatchl/Development/github/hoot-ui/js/hoot/control/Validation.js:
  252                      } else {
  253                          //console.log('must wait for relation to load');
  254:                         context.loadEntity(rid, function(err, ent) {
  255                              relation = ent.data[0];
  256                              //Temp workaround to load member until https://github.com/ngageoint/hootenanny/issues/324
  ...
  260                              if (!feature) {
  261                                  //console.log('must wait for feature to load');
  262:                                 context.loadEntity(mid, function(err, ent) {
  263                                      loadFeature();
  264                                  }, mapid, layerName);

/home/bhatchl/Development/github/hoot-ui/js/id/id.js:
  110      };
  111  
  112:     context.loadEntity = function(id, callback, mapId, layerName) {
  113          function done(err, result) {
  114              entitiesLoaded(err, result);

3 matches across 2 files


Searching 297 files for "context.zoomToEntity" (regex)

/home/bhatchl/Development/github/hoot-ui/js/id/behavior/hash.js:
   66          if (location.hash) {
   67              var q = iD.util.stringQs(location.hash.substring(1));
   68:             if (q.id) context.zoomToEntity(q.id.split(',')[0], !q.map);
   69              if (q.comment) context.storage('comment', q.comment);
   70              hashchange();

/home/bhatchl/Development/github/hoot-ui/js/id/id.js:
  126      };
  127  
  128:     context.zoomToEntity = function(id, zoomTo) {
  129          if (zoomTo !== false) {
  130              this.loadEntity(id, function(err, result) {

/home/bhatchl/Development/github/hoot-ui/js/id/ui/feature_list.js:
  224                  context.enter(iD.modes.Select(context, [d.entity.id]));
  225              } else {
  226:                 context.zoomToEntity(d.id);
  227              }
  228          }

3 matches across 3 files
```
I'm not sure how to get a feature id in the url hash, not what the feature_list actually is.  

I tested the conflation review tag table, and if the review feature is not in the visible map extent, it will pan to recenter.  However if the review feature is in the visible extent but not centered, it will do nothing.  Is this behaving as designed?

**Comment by sisskind** [comment]
I believe that is the desired outcome.  If that is the case, we should be good to merge.  Sound good?

**Pull request merged**
