### PR TITLE
#356 Alert user that deleting layer will delete bookmarks

### PR DESCRIPTION
**Pull request by sisskind**
#356 

Also may mitigate ngageoint/hootenanny#501

### CODE REVIEW

**Comment by sisskind** [comment]
@brianhatchl Can you review?  Should receive notification that the dataset has review bookmarks that will also be deleted.

**Comment by brianhatchl** [comment]
Looking at the diff, I think it would be much more bulletproof if the delete map service call was updated to delete review bookmarks internally.  Here we are relying on the UI to call delete review bookmark before calling delete map.  Thoughts?

**Comment by sisskind** [comment]
@brianhatchl do not disagree at all.  this was an initial band-aid from the UI side, but I think the best fix is what you described above.

**Comment by brianhatchl** [comment]
K, I'll review this with that in mind and add another ticket to make the delete map service more robust.

**Pull request merged**
