### PR TITLE
Add advanced options label under Conflate

### PR DESCRIPTION
**Pull request by rmrice**
screenshot from 2017-01-26 14 19 04

ngageoint/hootenanny-ui#833

### CODE REVIEW

**Comment by rmrice** [comment]
run cucumber

**Comment by sputnam** [comment]
run cucumber

**Comment by rmrice** [comment]
run cucumber

**Comment by rmrice** [comment]
It's failing on this, like #837 was:

```stale element reference: element is not attached to the page document
  (Session info: chrome=49.0.2623.87)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.13.0-107-generic x86_64) (Selenium::WebDriver::Error::StaleElementReferenceError)
features/review_bookmarks.feature:85:in `And I should see "Cucumber Bookmark 2" bookmark first and "Cucumber Bookmark 1" bookmark second'

Failing Scenarios:
cucumber features/review_bookmarks.feature:77 # Scenario: Filter Bookmarks
```

@brianhatchl is this related to https://github.com/ngageoint/hootenanny/pull/1375?

**Comment by brianhatchl** [comment]
run cucumber

**Pull request merged**
