### PR TITLE
#321 Toggle Layers added to radial menu

### PR DESCRIPTION
**Pull request by sisskind**
#321

### CODE REVIEW

**Comment by sisskind** [comment]
@brianhatchl or @treycaldwell can you review?  Added toggle icon to radial menu as well as changed code to call when merged layer exists.  The rotate or change road direction should now work even when in review mode.

**Comment by mjeffe98** [comment]
@sisskind I did not see what the icon used to look like in the radial menu but was it different from this screencap?  There's no icon in the button

image

**Comment by sisskind** [comment]
Did you run make on Hoot?

This electronic communication and any attachments may contain confidential and proprietary information of DigitalGlobe, Inc. If you are not the intended recipient, or an agent or employee responsible for delivering this communication to the intended recipient, or if you have received this communication in error, please do not print, copy, retransmit, disseminate or otherwise use the information. Please indicate to the sender that you have received this communication in error, and delete the copy you received.

DigitalGlobe reserves the right to monitor any electronic communication sent or received by its employees, agents or representatives.

**Comment by mjeffe98** [comment]
yes..  this is rebuilt via vagrant provision

**Comment by sisskind** [comment]
Ok - may need to run make on Hoot-UI as well. @brianhatchl is this not done already?

**Comment by brianhatchl** [comment]
Not by anything in the main hoot Makefile or in Vagrant provision.  If there are make artifacts created for icons in hoot-ui you probably need to commit those.

**Comment by sisskind** [comment]
Will do in a bit - @mjeffe98 stand by

**Comment by sisskind** [comment]
c54e99793d50c0f05803827663b35641a545edb7

Using the layers icon for toggle:

**Comment by mjeffe98** [comment]
this is fixed now

**Pull request merged**
