### PR TITLE
Fixed 1868. added folder tree for translations

### PR DESCRIPTION
**Pull request by bobi7**
ref #1868

### CODE REVIEW

**Comment by bobi7** [comment]
- [x] less of a gap between the buttons at the top
- [x] add public/private folders toggle button
- [x] change 'create folder' to 'add folder' to better match with the datasets panel

**Comment by brianhatchl** [comment]
It seems attempting to move a folder the user does not own needs to populate the error alert.  The http response shows "You must own both folders to move it" and the alert popup appears but it is empty.

**Comment by brianhatchl** [comment]
I see one more place where error message needs to be alerted.  When moving a translation script user does not own to a folder they do own.

**Comment by brianhatchl** [comment]
I noticed that there is a context menu for Moving/Renaming a translation script but the popup only allows it to be moved.  The View translation option opens a form that lets description and the script to be edited, but does not allow the name or the path to be edited.  Maybe these could be combined to allow moving/renaming/editing in the view form or at least made consistent.

**Comment by brianhatchl** [comment]
I also noticed a weirdness when moving a translation owned by my user from a public folder to a private folder, the highlighting remained blue (indicating public).  I think it should inherit the visibility of it's parent folder.

**Comment by bobi7** [comment]
fixed the inherit parent folder visibility in services code

**Review by brianhatchl — APPROVED** [review]
LGTM :soccer: :trophy:

**Pull request merged**
