### PR TITLE
hitting enter adds folder instead of refreshing

### PR DESCRIPTION
**Pull request by rmrice**
added keypress function to input for add folder (same code as onclick).

### CODE REVIEW

**Comment by sisskind** [comment]
test this please

**Comment by sisskind** [comment]
@rmrice Challenge for you:  Instead of writing the "enter" submit and the "apply" button click functionality twice (since it is the same), could you write a function that captures it once and then call it from either event?  There are a few examples of this in the code I can point you to.

**Comment by rmrice** [comment]
@sisskind sure, can you point me to the examples?

**Comment by sisskind** [comment]
https://github.com/ngageoint/hootenanny-ui/blob/master/js/hoot/view/utilities/Dataset.js#L184

The _deleteLayerCallback is a variable that is a function, which can be called from within another function.  You could call the new function from within the button click and the enter key.

**Comment by rmrice** [comment]
updated Folder.js to call a _submit function when enter key is triggered and on clicking the Add Folder button

**Comment by sisskind** [comment]
test this please

**Pull request merged**
