### PR TITLE
#598 added spinner to indicate loading import; removed progress bar

### PR DESCRIPTION
**Pull request by rmrice**
When you do a bulk import a spinner icon will indicate uploading rather than a progress bar (right click on add dataset to access bulk import).

### CODE REVIEW

**Comment by brianhatchl** [comment]
jenkins please run cucumber

**Comment by brianhatchl** [comment]
jenkins, please run cucumber again

**Comment by brianhatchl** [comment]
jenkins let's run cucumber once more

**Comment by brianhatchl** [comment]
grumble

**Comment by sisskind** [comment]
hey jenkins, i know its been a long day, but can you run cucumber again

**Comment by brianhatchl** [comment]
jenkins, please run cucumber

**Comment by brianhatchl** [comment]
run cucumber

**Comment by brianhatchl** [comment]
run cucumber

**Comment by sisskind** [comment]
run cucumber

**Comment by sisskind** [comment]
#598

**Comment by brianhatchl** [comment]
jenkins run cucumber

**Comment by brianhatchl** [comment]
please run cucumber

**Comment by brianhatchl** [comment]
pretty please run cucumber

**Comment by brianhatchl** [comment]
run cucumber

**Pull request merged**
