### PR TITLE
grail ui tools added

### PR DESCRIPTION
**Pull request by bobi7**

### CODE REVIEW

**Comment by brianhatchl** [comment]
Need to update test expectation for `hoot-ui/test/hoot/spec/toolbar/tools.js`

**Comment by brianhatchl** [comment]
@bobi7 can you post a screenshot of the new changeset summary table?

**Comment by bobi7** [comment]
Screen Shot 2019-05-31 at 11 09 41 AM

**Comment by brianhatchl** [comment]
Ah, do we need to show another table or update the numbers if Apply Tag Differential is checked?

Also, that check does not appear if the changeset is the the result of a normal conflation right?

**Comment by bobi7** [comment]
correct normal conflation in UI doesn't make a tags osc file so no check. Derive differential changeset has to be run for that to occur

**Pull request merged**
