### PR TITLE
#586 added tooltips for translation descriptions

### PR DESCRIPTION
**Pull request by rmrice**
On translations page you should see just the shortname of the translation and a tooltip of the description / longer name when you hover.

For some reason setting the opacity is bumping down the trashcan icon. I removed it for now. Not sure if it's necessary (or having a trashcan is necessary? I'm not sure if there's a case in which someone would choose to remove a translation). If we want to make the trashcans more transparent again I can look further into this.

### CODE REVIEW

**Comment by brianhatchl** [comment]
jenkins, please run cucumber

**Comment by brianhatchl** [comment]
jenkins, please run cucumber

**Comment by brianhatchl** [comment]
jenkins, please re run cucumber

**Comment by rmrice** [comment]
Going to continue working on this

**Comment by rmrice** [comment]
- Added a class specific for translations tooltips (`transl`)
- Fixed the CSS so there is an exception for the translations tooltips (exception being that they're wider). 
- Was having another issue with empty tooltips popping up in the help menu because I was selecting `a`, but with the `transl` class it's no longer an issue

**Comment by brianhatchl** [comment]
I made some changes to the jenkins jobs config to try to mitigate this failure https://github.com/ngageoint/hootenanny/issues/944

jenkins please run cucumber

**Comment by brianhatchl** [comment]
different error this time, so jenkins please run cucumber

**Comment by rmrice** [comment]
Ran cucumber locally and it works

```
.................................................

6 scenarios (6 passed)
49 steps (49 passed)
1m14.594s
```

**Comment by brianhatchl** [comment]
The cucumber tests have been unreliable today, but I'm sure the translation feature needs updating for this PR.

Here is what I get when running locally:
```
vagrant@vagrant-ubuntu-trusty-64:~/hoot/test-files/ui$ xvfb-run --server-args="-screen 0, 1024x768x24" cucumber --format progress --strict features/translation_ingest_edit.feature 
/home/vagrant/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/platform.rb:166: warning: Insecure world writable dir /home/vagrant/hadoop/bin/ in PATH, mode 040777
............F    HTML screenshot: ./screenshot_2016-08-02-21-57-05.283.html
    Image screenshot: ./screenshot_2016-08-02-21-57-05.283.png


(::) failed steps (::)

expected #has_selector?("a", {:text=>"Cucumber Translation: Cucumber Test Translation"}) to return true, got false (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/custom_steps.rb:129:in `/^I should( not)? see a link "([^"]*)"$/'
features/translation_ingest_edit.feature:18:in `And I should see a link "Cucumber Translation: Cucumber Test Translation"'

Failing Scenarios:
cucumber features/translation_ingest_edit.feature:8 # Scenario: Ingest Translation

2 scenarios (1 failed, 1 passed)
13 steps (1 failed, 12 passed)
0m17.884s
```

**Comment by brianhatchl** [comment]
run cucumber

**Comment by sisskind** [comment]
run cucumber

**Comment by brianhatchl** [comment]
This cucumber failure is expected, please see above.

**Comment by rmrice** [comment]
I think I know why this is failing. The test is looking for a link containing the FULL name of the translation (translation name + description) when the change made (and the point of the ticket) was to HIDE the description, so now the link/a is just the short name. See below:

screenshot from 2016-08-03 15 28 48

So the test is looking for a link that says `"Cucumber Translation: Cucumber Test Translation"`, while the new link is just "Cucumber Translation" (name) with "Cucumber Test Translation" (description) in a tooltip.



```
 # features/step_definitions/custom_steps.rb:195
    And I should see a link "Cucumber Translation: Cucumber Test Translation"                                                                                                                             # features/step_definitions/custom_steps.rb:124
      expected #has_selector?("a", {:text=>"Cucumber Translation: Cucumber Test Translation"}) to return true, got false (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/custom_steps.rb:129:in `/^I should( not)? see a link "([^"]*)"$/'
      features/translation_ingest_edit.feature:18:in `And I should see a link "Cucumber Translation: Cucumber Test Translation"'
    HTML screenshot: ./screenshot_2016-08-03-19-21-54.735.html
    Image screenshot: ./screenshot_2016-08-03-19-21-54.735.png

  Scenario: Edit Translation                                                                                                                                                                              # features/translation_ingest_edit.feature:20
    When I click the "folder" icon under the "Cucumber Translation: Cucumber Test Translation" link                                                                                                       # features/step_definitions/custom_steps.rb:19
      Unable to find css "a" with text "Cucumber Translation: Cucumber Test Translation" (Capybara::ElementNotFound)
      ./features/step_definitions/custom_steps.rb:20:in `/^I click the "([^"]*)" icon under the "([^"]*)" link$/'
      features/translation_ingest_edit.feature:21:in `When I click the "folder" icon under the "Cucumber Translation: Cucumber Test Translation" link'
    And I fill "translationDescription" input with "Jakarta Coastline"                                                                                                                                    # features/step_definitions/custom_steps.rb:295
    And I fill "translationText" textarea with: var attributeMapping = {"jakarta_raya_coastline": {"NATURAL": {"water": "other"}}};var fcode;var schema;                                                  # features/step_definitions/custom_steps.rb:300
    And I add to "translationText" textarea with: //translateToOsm - takes 'attrs' and returns OSM 'tags'                                                                                                 # features/step_definitions/custom_steps.rb:305
    And I add to "translationText" textarea with: var translateToOsm = function(attrs, layerName) {return translation_assistant.translateAttributes(attrs, layerName, attributeMapping, fcode, schema);}; # features/step_definitions/custom_steps.rb:305
    Then I click first "Save Edits"                                                                                                                                                                       # features/step_definitions/custom_steps.rb:195
    And I should see a link "Cucumber Translation: Jakarta Coastline"                                                                                                                                     # features/step_definitions/custom_steps.rb:124
    HTML screenshot: ./screenshot_2016-08-03-19-21-57.187.html
    Image screenshot: ./screenshot_2016-08-03-19-21-57.187.png

  Scenario: Delete Translation                                                             # features/translation_ingest_edit.feature:29
    When I click the "trash" icon under the "Cucumber Translation: Jakarta Coastline" link # features/step_definitions/custom_steps.rb:19
      Unable to find css "a" with text "Cucumber Translation: Jakarta Coastline" (Capybara::ElementNotFound)
      ./features/step_definitions/custom_steps.rb:20:in `/^I click the "([^"]*)" icon under the "([^"]*)" link$/'
      features/translation_ingest_edit.feature:30:in `When I click the "trash" icon under the "Cucumber Translation: Jakarta Coastline" link'
    And I accept the alert                                                                 # features/step_definitions/custom_steps.rb:519
    And I should not see a link "Cucumber Translation: Jakarta Coastline"                  # features/step_definitions/custom_steps.rb:124
    HTML screenshot: ./screenshot_2016-08-03-19-21-59.518.html
    Image screenshot: ./screenshot_2016-08-03-19-21-59.518.png

Failing Scenarios:
cucumber features/translation_ingest_edit.feature:8 # Scenario: Ingest Translation
cucumber features/translation_ingest_edit.feature:20 # Scenario: Edit Translation
cucumber features/translation_ingest_edit.feature:29 # Scenario: Delete Translation

4 scenarios (3 failed, 1 passed)
23 steps (3 failed, 8 skipped, 12 passed)
0m18.837s

```

**Comment by brianhatchl** [comment]
That's right.  So the cucumber test needs to be updated.  The difficulty is that the test feature is in the main hoot repo, so you'll have to create another PR updating the test and with the hoot-ui submodule commit for this hoot-ui PR branch.  Then the test should pass and you can merge both.

**Comment by rmrice** [comment]
run cucumber

**Comment by rmrice** [comment]
bitmoji

**Comment by jcp2236** [comment]
bitmoji

**Comment by briandaviddavidson** [comment]
Tooltips look good :+1:

**Pull request merged**
