### PR TITLE
Add diff conflate type to UI

### PR DESCRIPTION
**Pull request by sisskind**

### CODE REVIEW

**Comment by mschicker** [comment]
run cucumber

**Comment by sputnam** [comment]
run cucumber

**Comment by mschicker** [comment]
run cucumber

**Comment by sputnam** [comment]
run cucumber

**Comment by sputnam** [comment]
run cucumber

**Comment by sputnam** [comment]
run cucumber

**Comment by sputnam** [comment]
run cucumber

**Comment by sputnam** [comment]
run cucumber

**Comment by sputnam** [comment]
run cucumber

**Comment by sisskind** [comment]
https://github.com/ngageoint/hootenanny-ui/issues/940

**Pull request merged**
