### PR TITLE
Blue highlighted review features not displaying at default zoom level…

### PR DESCRIPTION
**Pull request by jchoi1267**
… for longer linear features #167

### CODE REVIEW

**Comment by brianhatchl** [comment]
The blue review against feature is fixed, but I do see each vertex of the way being rendered, which I don't think we want.
screenshot from 2016-01-13 10 46 39
This may be due to disabling autoHidden feature filtering when in review mode:
https://github.com/ngageoint/hootenanny-ui/blob/develop/js/id/renderer/map.js#L144-L146

**Comment by brianhatchl** [comment]
Hmm, that's not it.  But is seems the vertices should only be visible when the feature is selected.

**Comment by mjeffe98** [comment]
@brianhatchl seeing the vertices maybe related to https://github.com/ngageoint/hootenanny-ui/issues/144.  It seems that the merged features that are green display vertices because those are nodes that have been added during conflation but pink/orange highlighed segments will not have the vertices pop-out like that.

**Comment by brianhatchl** [comment]
The vertices disappear when you zoom in though.  And will reappear (though with a different symbol) when the feature is selected.

**Comment by brianhatchl** [comment]
As this is most likely a symptom of loading members of a relation feature, like that described in #144, I'm going to go ahead and merge.

**Pull request merged**
