### PR TITLE
Measure label fix

### PR DESCRIPTION
**Pull request by sisskind**

### CODE REVIEW

**Comment by mikejeffe** [comment]
I assume this will address the issue of the label disappearing on Line measurements.  Doesn't appear to be a problem with Area measurements as the distance label remains after zooming in/out.

**Comment by sisskind** [comment]
test this please

**Comment by mikejeffe** [comment]
@sisskind I don't see this commit in the release (0.2.26_728_ga44f271) or a git log entry.  Did you submodule sync?  I've tried to pull again but there are no new commits showing up for this branch.

**Comment by sisskind** [comment]
@mikejeffe It appears it got overwritten.  Recommitting and syncing now.

**Pull request merged**
