### PR TITLE
#514

### PR DESCRIPTION
**Pull request by briandaviddavidson**
I added an `I` icon to the label and changed it back to it's original functionality.

After looking at location, placement, function, etc., it made the most sense to change the label back to it's original functionality (showing the user the about tab). The `I` now helps to give the user some context that the area is clickable.

Ticket: #514 
Cancels out: #516

### CODE REVIEW

**Comment by sisskind** [comment]
Going to keep this open temporarily until we can conduct UI/UX survey

**Comment by sisskind** [comment]
Let's hold off on the icon for now, as we may go under a larger refactoring of UI in future.

**Comment by briandaviddavidson** [comment]
Should be good to merge :+1:

**Comment by sisskind** [comment]
test this please

**Pull request merged**
