### PR TITLE
Disable tag filtering on feature copy/paste

### PR DESCRIPTION
**Pull request by brianhatchl**

### CODE REVIEW

**Comment by brianhatchl** [comment]
@sisskind @mikejeffe if you agree on this change, the PR is ready to review and merge

**Comment by sisskind** [comment]
:+1:

**Comment by sisskind** [comment]
@mikejeffe agree?

**Comment by sisskind** [comment]
@mikejeffe agree?

**Comment by mikejeffe** [comment]
sorry for some reason I didn't get this notification.  yes that's valid.

**Pull request merged**
