### PR TITLE
304

### PR DESCRIPTION
**Pull request by jcp2236**
Add placeholder text "N/A" in review table for conflated features

### CODE REVIEW

**Comment by brianhatchl** [comment]
I'm not sure I like the 'N/A' solution to #304.
screenshot from 2016-11-23 11 20 32
These could easily be confused with tag values IMO.

Maybe non-breaking spaces `&nbsp;` would make the column wider but still appear blank instead?

Also, this PR branch appears to have commits from https://github.com/ngageoint/hootenanny-ui/pull/784 mixed in, which should be removed.

**Comment by jcp2236** [comment]
Good idea, I like the idea of widening the column. I'll get the old commits removed, I noticed that the other day too. I haven't deleted old commits before, should I use the command `git rebase -i HEAD~4` or am I way off track?

**Comment by brianhatchl** [comment]
When working on a new feature, you should create a new feature branch off of the develop branch before making any changes and commits:
```
git checkout develop
git pull
git checkout -b my_new_feature_branch
```
Maybe you did a new branch checkout from the other feature branch instead of develop?

**Comment by jcp2236** [comment]
Yeah, I was working on both, and it looks like I got the 'wires crossed'.

**Comment by jcp2236** [comment]
I was asking about how to delete the two earliest commits in this branch, which were meant for #756, not #304

**Comment by brianhatchl** [comment]
might just be best to recreate the branch and cherry-pick the intended commit.  either way git history would get changed, so deleting the remote branch will be necessary too.  not sure if the pull request needs to be deleted as well when removing the remote branch.

**Comment by jcp2236** [comment]
Alright, I thought that might be the way I had to go. Thanks for the help.

**Pull request closed without merging**
