### PR TITLE
#515: Add min and max width to sidebar

### PR DESCRIPTION
**Pull request by briandaviddavidson**
Created a feature branch off of `develop` instead of `master`

Ticket: #515

### CODE REVIEW

**Comment by sisskind** [comment]
@briandaviddavidson think the sidebar should start at smallest width to save screen size.  Thoughts?

**Comment by briandaviddavidson** [comment]
@sisskind It should still start at 400px. Does it not?

**Comment by sisskind** [comment]
When I run 515 branch, it is defaulting to 664.44px.  Unsure if it is being overwritten by something else.

**Comment by briandaviddavidson** [comment]
Give that a try. That should fix it.

**Comment by sisskind** [comment]
Great job.

**Pull request merged**
