### PR TITLE
Export options

### PR DESCRIPTION
**Pull request by brianhatchl**
See https://github.com/ngageoint/hootenanny-ui/pull/948 for a PR to the wrong target branch.

### CODE REVIEW

**Comment by sisskind** [comment]
```
Failing Scenarios:
cucumber features/hide_map_features.feature:3 # Scenario: I can hide map features in review mode
```

**Comment by brianhatchl** [comment]
That's an old test result.  Not sure why it linked up to the new PR.  New cuke test should kick off momentarily.

**Comment by sisskind** [comment]
Thanks @brianhatchl

**Comment by brianhatchl** [comment]
run :cucumber:

**Comment by brianhatchl** [comment]
Now it's the same failure that @sputnam reported on develop.  Will wait for https://github.com/ngageoint/hootenanny/pull/1993 to be merged before running again.

I also tweaked the jenkins job config because it looked like the UI code was getting checked out but not built into the dist file that actually gets deployed.  So its possible the ui jobs weren't actually testing the UI PR code since we moved to deploying the dist js file back in July.

:scream:

**Comment by brianhatchl** [comment]
run :cucumber:

**Comment by brianhatchl** [comment]
that's my config error.

run :cucumber:

**Comment by brianhatchl** [comment]
run :cucumber:

**Pull request merged**
