### PR TITLE
fixes for #499

### PR DESCRIPTION
**Pull request by brianhatchl**
Add presets for MGCP and change schema filter behavior to only show presets for selected schema

### CODE REVIEW

**Comment by brianhatchl** [comment]
@sisskind can you try this?  The search is returning results, but they looks like pretty poor matches for the search term used.

1. Add a new point to the map.
2. Choose the TDS or MGCP schema in the drop down.
3. Type something like "building" or "hospital" in the Search bar.

**Comment by briandaviddavidson** [comment]
I went in, added a point, switched to TDSv40/TDSv61 and was able to search for building and have building be the first option, but I couldn't get the same from MGCP. Is that expected @brianhatchl?

cc @sisskind

**Comment by sisskind** [comment]
Can confirm that something is awry with MGCP.  TDS works, but appears that MGCP is returning same results regardless of search term (Ferry Crossing Point Feature, Extraction Mine Point Feature, Quarry Point Feature...).

Upon further investigation, is it possible that MGCP is being searched against feature code and not description?

image

image


image

**Comment by sisskind** [comment]
@briandaviddavidson @brianhatchl working off of hoot develop branch

**Comment by sisskind** [comment]
...and after more discussion, it is possible that what is aforementioned is a bug that already existed and has nothing to do with this ticket.  If that is the case, we should look into creating a new ticket to solve issue.

**Comment by brianhatchl** [comment]
Please merge, will move this issues described above into new ticket

**Pull request merged**
