### PR TITLE
Bulk export tool

### PR DESCRIPTION
**Pull request by sisskind**
- https://github.com/ngageoint/hootenanny-ui/issues/919
- https://github.com/ngageoint/hootenanny-ui/issues/920

### CODE REVIEW

**Comment by sisskind** [comment]
@brianhatchl I'll fix the npm test later, but can you review in the meantime?

**Comment by sisskind** [comment]
@brianhatchl thanks for the feedback:

1. Maybe it should show disabled export context menu option when there are more than 10 selected datasets?
**Good idea, will implement.  Right now I believe it will not appear.**

It doesn't seem to work on a folder with a subfolder (get no datasets).
Or a right-clicking the subfolder directly:
**Will take a look**

Bulk export downloads multiple files (not a single zip). Was that what was asked for?
**Was done that way out of existing code to meet requirement.  Just got VOC and said that either was good, but going to one zip file would be preferred if possible.  Question -- would this blow browser memory?**

**Comment by sisskind** [comment]
@brianhatchl Nested folder issue should be solved.

**Comment by brianhatchl** [comment]
run :cucumber:

**Comment by brianhatchl** [comment]
death by :cucumber:

**Comment by sisskind** [comment]
why does 🥒 hate this pull request???

**Comment by brianhatchl** [comment]
Jenkins be a good :boy: and run :cucumber:

**Comment by brianhatchl** [comment]
cuke tests have failed on a different test/step each of the last four times.  :angry:

**Comment by sisskind** [comment]
No one likes you 🥒

**Comment by rmrice** [comment]
run 🥒 (i like you)

**Comment by sisskind** [comment]
@rmrice 🥑 !== 🥒

**Comment by sisskind** [comment]
@brianhatchl at what point can we merge in and chalk it up to cucumber on Jenkins being wonky?  Would like to include in next release that @sputnam is planning on cutting Monday.

**Comment by sisskind** [comment]
And while we are at it... run 🥒

**Comment by rmrice** [comment]
death by cucumber

**Comment by brianhatchl** [comment]
This can be the last try.

**Comment by brianhatchl** [comment]
Ha!
>Could not update commit status of the Pull Request on GitHub.
java.net.SocketTimeoutException: connect timed out

**Comment by rmrice** [comment]
literal death by cucumber :hocho: :hocho: :hocho: :hocho: :hocho: :hocho: :hocho: :hocho: :hocho: :hocho: :hocho:

**Comment by brianhatchl** [comment]
I think this cuke feature needs updating for these changes, import_export_delete_osm_dataset.feature

**Comment by brianhatchl** [comment]
Actually, looks like the expectation is correct and the UI isn't updated.  Investigating

**Comment by brianhatchl** [comment]
Needed to merge origin/develop to get UI updates the cucumber feature expected.

**Comment by sisskind** [comment]
Dear :cucumber:,

All I wanted to do was something nice.  You are not.

Please run 🥒 and pass so we can all get on with our lives.

Best,

😞

**Comment by brianhatchl** [comment]
Will tackle the cuke test failures (caused by PRs already merged into develop because of a jenkins job misconfiguration lead to false passes) in a new ticket/branch

**Pull request merged**
