### PR TITLE
#300 Bulk Import Improvements

### PR DESCRIPTION
**Pull request by sisskind**
Bulk import improvements (#300)

### CODE REVIEW

**Comment by sisskind** [comment]
test this please (@sputnam is something wrong with jenkins?)

**Comment by sisskind** [comment]
test this please

**Comment by sisskind** [comment]
test this please

**Comment by brianhatchl** [comment]
seems like a legit failure, I don't see "Import Multiple Datasets" button in the screenshot:

screenshot_2016-10-28-09-54-05 168

**Comment by sisskind** [comment]
Will fail until fix to #771

**Pull request merged**
