### PR TITLE
897 stack alerts vertically

### PR DESCRIPTION
**Pull request by abalosc1**
vertical alerts

### CODE REVIEW

**Comment by rmrice** [comment]
run :cucumber:

**Comment by abalosc1** [comment]
tests ran fine locally

**Comment by rmrice** [comment]
```
expected #has_content?("HideMapFeaturesCucumber") to return true, got false (RSpec::Expectations::ExpectationNotMetError)

./features/step_definitions/custom_steps.rb:512:in `/^I wait ([0-9]*) "([^"]*)" to see "([^"]*)"$/'

./features/support/hooks.rb:43:in `block in <top (required)>'

features/hide_map_features.feature:20:in `Then I wait 3 "minutes" to see "HideMapFeaturesCucumber"'



Failing Scenarios:

cucumber features/hide_map_features.feature:3 # Scenario: I can hide map features in review mode
```

pretty sure it's a latency thing.

**Comment by rmrice** [comment]
@sisskind @brianhatchl have you seen this before? Looks like the conflated dataset doesn't show up in the side panel.

**Pull request merged**
