### PR TITLE
Generate code coverage report for mocha tests

### PR DESCRIPTION
**Pull request by brianhatchl**
refs #413

### CODE REVIEW

**Comment by brianhatchl** [comment]
run `npm run cover` to generate the code coverage report for js/id and js/hoot source files.

**Comment by sisskind** [comment]
@brianhatchl what should the output be?  Got the following:
```  1044 passing (10s)
  3 pending```

**Comment by brianhatchl** [comment]
It generates a coverage report in coverage/ and should launch the index page in a browser.
screenshot from 2016-05-03 08 55 24

**Comment by sisskind** [comment]
duh.  See that now.  Very cool.  Assuming that if I see this it is safe to merge into develop?

**Comment by sisskind** [comment]
@brianhatchl Will update hoot-ui splash page with this info.  Do we need to submit istanbul for approval or is it already included?

**Comment by brianhatchl** [comment]
This is a dev dependency, so shouldn't be included in a deployed system.  The node_modules folder is ignored by git.

**Comment by sisskind** [comment]
Rock and roll.

**Pull request merged**
