### PR TITLE
Add logo to header

### PR DESCRIPTION
**Pull request by rmrice**
https://github.com/ngageoint/hootenanny/issues/1341

### CODE REVIEW

**Comment by rmrice** [comment]
screenshot from 2017-01-19 09 56 19

**Comment by brianhatchl** [comment]
I want the stitching font.

**Comment by sisskind** [comment]
@brianhatchl

**Comment by sisskind** [comment]
Cucumber test passed on jenkins, and there is no reason that any of the code added would effect other tests.  Approving.

**Pull request merged**
