### PR TITLE
Merging #264 with develop

### PR DESCRIPTION
**Pull request by sisskind**
#264

### CODE REVIEW

**Comment by brianhatchl** [comment]
More related to the upstream merge, but the first thing I notice right away is that the brightness control does not work and there are 1 pixel gaps between the basemap tiles.  (This is using Bing).

**Comment by sisskind** [comment]
@brianhatchl See that as well.  Will create new ticket for those issues.

**Comment by brianhatchl** [comment]
- When I select a random POI
- Choose Show related reviews from the radial menu
- Click one of the related reviews
- And click Resolved

It does resolve the correct review pair.  However I'd still like to see the UI maintain the selected point and make one of the other related reviews the next active review.

**Comment by sisskind** [comment]
@brianhatchl will traverse to next review in associated relation now.  Ready for your review and, upon approval, merging into develop.

**Comment by sisskind** [comment]
@brianhatchl believe this should meet your requirement...

**Comment by sisskind** [comment]
@brianhatchl next iteration ready for review

**Comment by brianhatchl** [comment]
Looking good!

Minor thing, the Shift-R shortcut only seems to work once the related reviews have been shown via the radial menu.

We can track that as another issue if you want and merge this.  Sound good?

**Comment by brianhatchl** [comment]
I take that back.  I realize I have to select one of the POI features first for the shortcut to work.  Merging.

**Pull request merged**
